Algoritmo "3° Desafio"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2020
Var
// Seção de Declarações das variáveis
//3° Desafio da atividade02
x:caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
leia(x)

Fimalgoritmo