algoritmo "1°_Desafio "

var
num: inteiro

inicio
// Seção de Comandos
   escreva ("Digite um número: ")
leia(num)
 se (num <= 0) entao
   escreval ("O número não esta no Intervalo de [1 a 10]")
   escreval ("Valor Inválido")
 senao
 se (num >= 11)entao
   escreval ("O número não está no intervalo de [1 a 10]")
   escreval ("Valor Inválido")
 senao
 se (num <= 10) entao
   escreval ("O número esta no intervalo de [1 a 10]")
   escreval ("Valor Válido")

fimse
fimse
fimse

fimalgoritmo
