Algoritmo "7°_Desafio"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/04/2020
Var
// Seção de Declarações das variáveis 
num:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   num<-0
   enquanto (num <=100) faca
      escreva(num)
      num<- num+2

   fimenquanto
   

Fimalgoritmo