Algoritmo "8°_Desafio"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/04/2020
Var
// Seção de Declarações das variáveis 
   parar:caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   enquanto parar <> "f" faca
   escreva("A mensagem será interrompida quando a tecla f for pressionada. ")
   leia(parar)
fimenquanto
Fimalgoritmo